#NumPy Challenge

Create a NumPy ndarray object by using this list of numbers [7,8,4,5,1,2].


In [3]:
import numpy as np
arr = np.array([7, 8, 4 ,5 ,1, 2])
print(arr)
print(type(arr))

[7 8 4 5 1 2]
<class 'numpy.ndarray'>


Using slicing print the elements from index 3 to the end of the array.



In [0]:
print(arr[3:])

[5 1 2]


Using slicing print all the elements except the last one.



In [0]:
print(arr[:-1])

[7 8 4 5 1]


Using slicing print the elements from index 1 to index 4 of the array.



In [0]:
print(arr[1:4])

[8 4 5]


Reshape the array into a 3 rows and 2 cols (3,2).



In [0]:
arre = np.array([[7, 8], [4, 5], [1, 2]])
print(arr)
print(arr.ndim)

[7 8 4 5 1 2]
1


Print all the array elements one by one (iterating).



In [0]:
for x in arr:
  print(x)

7
8
4
5
1
2


Create a new NumPy ndarray object by using this list of numbers [0,6,9].



In [0]:
arreg = np.array([0, 6, 9])
print(arreg)

[0 6 9]


Join the two arrays.



In [0]:
ar = np.concatenate((arr, arreg))
print(ar)

[7 8 4 5 1 2 0 6 9]


Using filtering print only the odd numbers of the joined array.



In [0]:
filter_ar = ar % 2 == 1

newar = ar[filter_ar]

print(filter_ar)
print(newar)

[ True False False  True  True False False False  True]
[7 5 1 9]


Sort the joined array elements.



In [0]:
print(np.sort(ar))

[0 1 2 4 5 6 7 8 9]


Store in an array the names of the months.



In [0]:
months = np.array(['January', 'Frebruary', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'])

Split the months array in 4 periods of 3 elements each one.



In [14]:
months2 = np.array_split(months, 4)
print(months2)

[array(['January', 'Frebruary', 'March'], dtype='<U9'), array(['April', 'May', 'June'], dtype='<U9'), array(['July', 'August', 'September'], dtype='<U9'), array(['October', 'November', 'December'], dtype='<U9')]


Create an array with genre information ['F','M','F','F','M','F'].



In [0]:
genre = np.array(['F', 'M', 'F', 'F', 'M', 'F'])

Find the indexes where the value is F.



In [14]:
genre2 = np.where(genre == 'F')
print(genre2)

(array([0, 2, 3, 5]),)


Store in an array the age information [18,20,19,23,19,20].



In [0]:
age = np.array([18, 20, 19, 23, 19,20])

Create a filter array with values < 20.



In [20]:
filter_age = age < 20

newage = age[filter_age]

print(filter_age)
print(newage)

[ True False  True False  True False]
[18 19 19]


Change the 3 index element with a value of 22



In [25]:
age[3]=22
print(age)

[18 20 19 22 19 20]


Print the 4 index element.

In [24]:
print(age[4])

19
